name: Verify dist is up to date (npm run prepare)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  verify-dist:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - run: npm install

      - name: Rebuild dist (npm run prepare)
        run: npm run prepare

      - name: Verify no dist changes
        run: |

          if [ -n "$(git status dist --porcelain)" ]; then
            # Uncommitted changes
            git status dist --porcelain
            echo "::error::Uncommitted changes after npm run prepare.  Run 'npm run prepare' and commit any changes to ./dist."
            exit 1
          fi
